# ==============
# Config file for plugin MapSaver
# ==============
Language: "fr_FR"
Prefix: "&a[MapSaver] &f"
ServerName: "server"
Storage:
  Type: "mysql"
  TablePrefix: "MapSaver"
  Connection:
    Host: "localhost"
    Port: "3306"
    Database: "my_database"
    User: "my_user"
    Password: "my_password"
    UseSSL: true
Options:
  PageSize: 10
  DefaultVisibility: "PRIVATE"
  ConsumeEmptyMap: true
