main: fr.epicanard.mapsaver.MapSaverPlugin
description: Plugin for saving map in database
author: EpiCanard
authors:
  - EpiCanard
  - Ikkino
api-version: 1.16
commands:
  mapsaver:
    description: Main command to interact with MapSaver
    usage: "Usage: /mapsaver <action>"
    aliases:
      - maps
      - msaver
