main: fr.ikkino.mapsaver.MapSaverPlugin
name: MapSaver
description: Plugin for saving map in database
author: Ikkino
version: ${build.version}
api-version: 1.16
commands:
  mapsa:
    description: Main user command for map saver
    usage: "Usage: /mapsa <action>"